F3 done, but you need to change app/assets/javascripts/application.js //= require query.ui.effect-blind to //= require jquery-ui/effect-blind save, then restert server. to avoid couldn't find file 'jquery.ui.effect-blind'   (in /Users/uknowme/Programs/ruby/rails/depot/app/assets/javascripts/application.js:14) error